report_path: "reports/EDA_report.html"
train_data_path: "data/raw/train.csv"
model_path: "models/model.pkl"
features_transformer_path: "features_transformer/features_transformer.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 7
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
  numerical_features:
    - "age"
    - "sex"
    - "cp"
    - "trestbps"
    - "chol"
    - "fbs"
    - "restecg"
    - "thalach"
    - "exang"
    - "oldpeak"
    - "slope"
    - "ca"
    - "thal"
  features_to_drop:
  target_col: "target"
inference_params:
  source_data_path: "data/inference/source_data.csv"
  result_data_path: "data/inference/result_data.csv"
